### PR TITLE
[READY] Implement usage of countable stores in path mapping repositories

### PR DESCRIPTION
**Pull request by tgalopin**
Implement the Countable stores (https://github.com/webmozart/key-value-store/pull/13) in PathMapping repositories.

### CODE REVIEW

**Comment by tgalopin** [comment]
It seems there is a problem with the StyleCI parsing, look like a bug from the platform: https://styleci.io/analyses/zDML98

**Comment by tgalopin** [comment]
Well, what is happening now? Both Scrunitizer and StyleCI failed without reason ...

**Comment by webmozart** [comment]
Scrutinizer failed since Travis was not running. This is weird.

**Comment by GrahamCampbell** [comment]
I'm looking into StyleCI right now guys. Expect a fix soon. :)

**Comment by webmozart** [comment]
Thanks @GrahamCampbell! :)

**Comment by GrahamCampbell** [comment]
@webmozart All fixed. See https://github.com/puli/repository/pull/34.

**Comment by tgalopin** [comment]
So, what now?

**Comment by webmozart** [comment]
Looks good to me. Thanks @tgalopin! :)

**Pull request merged**
