### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This should fix all your issues with StyleCI.

**Comment by webmozart** [comment]
@GrahamCampbell Cool thanks! :) What was the problem?

**Comment by GrahamCampbell** [comment]
That missing brace was causing the fixed file to have a syntax error.

**Comment by webmozart** [comment]
Ah! Is there (in general) any way to debug such problems without needing your assistance?

**Comment by GrahamCampbell** [comment]
I manually disabled our linting process to highlight that issue. I'm about to ship that feature to production though, so soon you'll be able to just add `linting: false` to your config to highlight the exact issue.

**Comment by webmozart** [comment]
Ok :) Will there be a way to manually trigger a scan with a changed config? I don't really want to push two commits (`linting: false`, `linting: true`) every time there is a problem.

**Comment by GrahamCampbell** [comment]
> Ok :) Will there be a way to manually trigger a scan with a changed config? I don't really want to push two commits (linting: false, linting: true) every time there is a problem.

Absolutely. You can actually modify the config from in your browser you you don't have to push any commits. Just update the config in browser, then hit the analyze now button.

**Comment by webmozart** [comment]
Ah! I hadn't seen that, cool :) Thanks a lot!

**Comment by GrahamCampbell** [comment]
We shipped that feature yesterday with our redesign. :)

**Pull request merged**
